# Generated by Django 4.1.2 on 2022-10-08 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Podaj kod pocztowy np.:"44-444"', regex='^[0-9]+$')], verbose_name='zip code'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
